#!/bin/sh

dev=$1
mnt=$2
shift 2

if [ -z "$dev" -o -z "$mnt" ]; then
    echo "$0 <device> <mount>" 1>&2
    exit 1
fi

args=
[ -f "$dev" ] || args="-o loop"

/bin/mount $args "$dev" "$mnt" &&
/bin/mount --bind "$PWD" "$mnt/workspace" &&
/bin/mount --bind /etc/resolv.conf "$mnt/etc/resolv.conf" &&
/usr/sbin/chroot "$mnt" $*
/bin/umount "$mnt/workspace"
/bin/umount "$mnt/etc/resolv.conf"
/bin/umount "$mnt"
